# cloudbuild.yaml
# Build & Deploy Next.js SSR to Cloud Run using Dockerfile in repo root

substitutions:
  _SERVICE_NAME: "tpg-clinic-web"
  _REGION: "us-central1"
  _PLATFORM: "managed"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA",
      "-f", "Dockerfile",
      "."
    ]

  # 2) Push image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
    ]

  # 3) Deploy to Cloud Run with env variables
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
      "run", "deploy", "$_SERVICE_NAME",
      "--image", "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA",
      "--region", "$_REGION",
      "--platform", "$_PLATFORM",
      "--allow-unauthenticated"
    ]

images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
